# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
  end

  nodes_number = 3
  (1..nodes_number).each do |i|
    hostname = "node-#{i}"
    ip = "192.168.33.#{9+i}"
    config.vm.define hostname do |node|
      node.vm.hostname = hostname
      node.vm.box = "ubuntu/bionic64"
      node.vm.network "private_network", ip: ip
    end
  end
end
